version: '3.8'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass not_a_production_pass
    volumes:
      - redis:/data

volumes:
  postgres:
    name: backend-db